stages:
  - build

variables:
  MAJOR: 'test'

build-docker-image:
  stage: build
  image: docker:stable
  services:
    - docker:dind
  before_script:
    - apk add --no-cache tzdata
    - export TZ=Asia/Seoul
    - VERSION=$MAJOR.$CI_COMMIT_SHORT_SHA
    - IMAGE_TAG=$CI_REGISTRY_IMAGE:$VERSION
    - IMAGE_TAG_LATEST=$CI_REGISTRY_IMAGE:latest
    - BUILD_DATE=$(date +'%Y-%m-%d %H:%M:%S')
    - |
      echo "GIT_COMMIT_HASH='$CI_COMMIT_SHORT_SHA'" >> .env.*
  script:
    - echo "$CI_DEPLOY_PASSWORD" | docker login $CI_REGISTRY -u $CI_DEPLOY_USER --password-stdin
    - docker build -t $IMAGE_TAG -t $IMAGE_TAG_LATEST .
    - docker push $IMAGE_TAG
    - docker push $IMAGE_TAG_LATEST
  only:
    - main
    - cicd
